### ISSUE TITLE
Making compatible to other themes

### ISSUE THREAD

**Issue by AshiqKiron** [xwp/wp-customize-inline-editing#5]
Hi there, this plugin really takes the UX to next level, pretty sleek. I want to extend this feature to other front page text elements in my theme (https://wordpress.org/themes/tar/). Activated the plugin then I added 

`elseif ( 'tar' === get_template() ) {
$setting_element_selectors['welcomecta'] = '.welcome-text h2';
$setting_element_selectors['welcomep'] = '.welcome-text p';
` 
on php file and also added 

`add_theme_support( 'customize-inline-editing', array(
    'blogname' => '.site-title a',
    'blogdescription' => '.site-description',
    'welcomecta' => '.welcome-text h2',
    'welcomep'	=> '.welcome-text p'
    // ...) );` on function.php file

But it's not working, Is there anything that I missed ? And also how would suggest to bundle this feature in theme, I'd really appreciate if you can advice in this matter. Thanks and keep up the good work on customizer :)

**Comment by westonruter** [comment]
@AshiqKiron I'm not able to reproduce that issue. Modifying the plugin file is not needed. I was able to successfully add support for your two new settings via:

## Adding to theme's `functions.php`

```php
add_theme_support( 'customize-inline-editing', array(
	'blogname' => '.site-title a',
	'blogdescription' => '.site-description',
	'welcomecta' => '.welcome-text h2',
	'welcomep' => '.welcome-text p',
) );
```

## Adding to a theme's customizer include

(May also be directly in `functions.php`)

```php
add_action( 'customize_register', function( WP_Customize_Manager $wp_customize ) {
	$wp_customize->add_setting( 'welcomecta', array(
		'type' => 'option',
	) );
	$wp_customize->add_control( 'welcomecta', array(
		'section' => 'title_tagline',
		'type' => 'text',
		'label' => __( 'Welcome CTA' ),
	) );
	$wp_customize->add_setting( 'welcomep', array(
		'type' => 'option',
	) );
	$wp_customize->add_control( 'welcomep', array(
		'section' => 'title_tagline',
		'type' => 'text',
		'label' => __( 'Welcome text' ),
	) );
} );
```

## Adding to my theme's `header.php`

```php
<?php
$welcomecta = get_option( 'welcomecta' );
$welcomep = get_option( 'welcomep' );
if ( '' === trim( $welcomecta ) && is_customize_preview() ) {
	$welcomecta = __( '(Enter Welcome CTA here)' );
}
if ( '' === trim( $welcomep ) && is_customize_preview() ) {
	$welcomep = __( '(Enter Welcome P here)' );
}
?>
<?php if ( $welcomecta || $welcomep ) : ?>
	<div class="welcome-text">
		<h2><?php echo esc_html( $welcomecta ) ?></h2>
		<p><?php echo esc_html( $welcomep ) ?></p>
	</div>
<?php endif; ?>
```

**Comment by AshiqKiron** [comment]
This is great. Thanks a ton :+1:
